.github/workflows/dagster.yml
https://github.com/docker/build-push-action/pull/781
Addresses issue with GCR not supporting attestations. Ref: https://github.com/docker/buildx/issues/1533
Looks like we'll need to move to artifact registry before going to `docker/build-push-action@v4` or explicitly set `provenance: false` in v4.
=> fix: bump to latest version of docker build to address provenance issue

.github/workflows/docker_build_push.yml
This is needed because github actions in some repos (see [labelbox-webhooks](https://github.com/20treeAI/labelbox-webhooks/blob/main/.github/workflows/push_to_prod.yml#L23)) expect images to be tagged with the commit sha, so that they can pull the latest image and tag it appropriately for a release.
=> add commit sha tag to images when pushing to container registry

.github/workflows/cloudrun_deploy_optional_sentry.yml, .github/workflows/dagster.yml, .github/workflows/docker_build_push.yml, .github/workflows/yarn_build_test.yml, README.md, examples/cloudrun_deploy_optional_sentry.yml, examples/dagster.yml, examples/docker_build_push.yml, examples/yarn_build_test.yml
This is related to https://github.com/20treeAI/coregistration-tool/pull/72 
We've added workflows for building a yarn project and also for deploying to cloudrun! 🎉 And docs! We have docs now!
This will have to be squashed and merged because I did too many commits 🤷
=> adding reusable yarn workflow and cloudrun/sentry optionals

.github/workflows/dagster.yml
Looks like we can't set the reclaim policy for the PVC that posgres creates anywhere in the bitnami postgres helm chart (the one that is bundled with dagster), so according to [bitnami's postgres docs](https://github.com/bitnami/charts/tree/main/bitnami/postgresql#uninstalling-the-chart) we'll just need to have a step to clean up the old PVC in our reusable github-workflows.
=> Fix dev-env cleanup step: remove postgres pvc

.github/workflows/dagster.yml
Fixing failing dagster deploy: https://github.com/20treeAI/active-learning/actions/runs/4755600075/jobs/8465355280?pr=39
Fix is in latest version of vimeda/helm: 
* v1.7.0 release notes: https://github.com/vimeda/helm/releases/tag/v1.7.0
* PR for fix: https://github.com/vimeda/helm/pull/16/files
=> fix: failing helm deployment

.github/workflows/docker_build_push.yml
current version was causing node.js deprecation warnings in workflow summaries
=> Update docker_build_push google-github-actions/setup-gcloud action to latest version

.github/workflows/terraform.yml
Changing this, as the current `defaults.run.working-directory` produces an error because inputs is not declared yet, I think.
=> change `defaults.run.working-directory` to `jobs.id.defaults.workfing-directory`

.github/workflows/dagster-scheduled-workflow.yml, README.md, examples/dagster_nightly_rebuild.yml
Separating out the workflow to be less complicated and more consistent.
nightly builds would then go like this:
job1: build and test docker image -> tag for stage, commit hash -> deploy to stage
If job1 successful, job2: retag for for prod -> deploy to prod
I haven't added a notification step, but it would be nice to add a slack notification only if build fails 🤔
=> add scheduled workflow for dagster

.github/workflows/docker_build_push.yml
This is to deal with size issues as described here:
https://github.com/docker/build-push-action/issues/321
Thanks to @chanange for finding this!
=> Update docker_build_push.yml - add job.id.with.docker = driver

.github/workflows/cloudrun_deploy_optional_sentry.yml, README.md
Missing secret declaration causing workflows to fail.
[Example failed workflow](https://github.com/20treeAI/coregistration-tool/actions/runs/5088639825/jobs/9145391684)
=> fix: include optional secrets for creating a release in Sentry

.github/workflows/python_library_ci.yml
In https://github.com/20treeAI/risk_score/pull/365, we are importing the `risk_score` as a `dev` dependency so that we can validate the `run_config`s generated from the SDK to the actual job in `risk_score` itself.
However, `risk_score` depends on `viaduct`, which is currently installed using ssh, meaning the CI for the SDK needs ssh access when running in the CI.
=> Add option to provide SSH keys to Python CI

.github/workflows/docker_build_push.yml
Add docker layer caching: 
https://depot.dev/blog/docker-layer-caching-in-github-actions
=> perf: use google actions cache for docker layers

.github/workflows/docker_build_push.yml
Cacning does not work with the `docker` buildx driver, which is used by https://github.com/20treeAI/active-learning.
=> fix: caching does not work with docker backend

.github/workflows/python_library_ci.yml
This has been working nicely for repos that do not use this template.
=> perf: use mamba instead of conda

.github/workflows/python_dagster_ci.yml, .github/workflows/python_gdal_ci.yml, README.md, examples/python_gdal_ci.yml
Adding a shared workflow for usage in our GDAL python repositories.
Adding improvements e.g. caching, clarifying docs, new features take a lot of time because each GDAL python repo has their own, hardcoded CI workflow.
- **Check SDK and package version match**
Flag which tests if the SDK version and package version match (`poetry version -s`)
- **2 Test "Stages"**
Ability to run two individual sets of test combinations. 
Examples of where these two stages are useful:
- Run stage 1 (fast) tests in CI on each commit, stage 2 (slow) tests only on merge to `main` (currently needed in`data-ingestion`, `coregistration` and `image-inventory`)
- Run stage 1 (parallel) tests in parallel using `pytest-xdist` and stage 2 (dask) tests sequentially to avoid conflicts between `dask` and `pytest-xdist` …
=> Add GDAL python repository workflow

.github/workflows/deploy_mkdocs.yml, .github/workflows/python_gdal_ci.yml, .github/workflows/python_library_ci.yml, .github/workflows/yarn_build_test.yml
* bumps action versions
* bumps poetry version
* enables cache for libraries
* enables conditional disable for ssh and package install
* default env install location changed to /home/runner/miniconda3
lib test: https://github.com/20treeAI/geozarr/pull/131
gdal test: https://github.com/20treeAI/coregistration/pull/172
Downstream something might break if it does not have "provide_ssh_access" set.
=> ci: refactor, bump versions

.github/workflows/python_library_ci.yml
* Include conditionals in workflow steps that use conda so non-conda repos skip those steps
* Fix pytest conditional when xdist is not enabled
* Use conda env input when building conda env
=> Fix python CI workflow to support optional conda setup

.github/workflows/dagster.yml, .github/workflows/docker_build_push.yml
`active-learning` exhibited a gnarly issue after https://github.com/20treeAI/github-workflows/pull/96 went in:
```
ERROR: failed to solve: process "/bin/sh -c poetry install --only main -vvv --no-cache" did not complete successfully: listen unix /home/runner/setup-docker-action-ea9b13b3-db6b-4c53-bdf1-19bf02ffdc0a/data/tmp/.buildkit-ssh-sock2385055271/ssh_auth_sock: bind: invalid argument
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c poetry install --only main -vvv --no-cache" did not complete successfully: listen unix /home/runner/setup-docker-action-ea9b13b3-db6b-4c53-bdf1-19bf02ffdc0a/data/tmp/.buildkit-ssh-sock2385055271/ssh_auth_sock: bind: invalid argument
```
This fixes that issue. I think the `default` changed for the `ssh` parameter in docker with the …
=> fix: SSH auth

.github/workflows/dagster-scheduled-workflow.yml, .github/workflows/dagster.yml
The inclusion always pointed to main, this causes hard-to-debug issues when pointing to a tag (since you expect to use all jobs from that tag).
Reusable workflows support local links! https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
@alexberndt you'll like this.
=> fix: internal consistency

.github/workflows/docker_build_push.yml
The default tag here would be `docker.io/library/test-image:latest`.
Currently, `push: false` is set, but there is a risk that some enables that without tagging with our own repo first, so I am setting it just in case.
Removing the `default` ssh method broke the poetry install on some repos (e.g. `viaduct` install in `risk-score`).
It seems the `docker` driver wants the socket, but `docker-container` wants `default` here...
=> fix: set tag to avoid accidental push, ssh auth

.github/workflows/python_gdal_ci.yml, .github/workflows/python_library_ci.yml
* not doing this can cause issues with the version checks we have in place
=> fix: invalidate venv cache on pyproject.toml change

.github/workflows/dagster.yml
In dev envs changes are usually deployed in quick iterations. This change switches to dagster code-server to support dynamic reloading of the code server/user repo. 
Related issue: https://github.com/dagster-io/dagster/issues/12581
Support added in: https://github.com/dagster-io/dagster/pull/14377
=> feat: switch to codeServerArgs for Dagster to support dynamic reloading

.github/workflows/dagster-scheduled-workflow.yml
- s29 nightly build is failing due to lack of space
=> feat: clear space on nightly builds

.github/workflows/docker_build_push.yml, README.md
Add an input to the shared workflow that allows for passing a non-standard context (not `.`) to Docker build workflows
=> Add a context input to allow for building multiple services

.github/workflows/docker_build_push.yml, .github/workflows/yarn_build_test.yml, examples/yarn_build_test.yml
Optional config value to point to the package directory, defaults to `.`. Needed to support Corgi, since it's a monorepo and the frontend is located at `./client/`
It also modifies the `docker_build_push` workflow to use the parameterised context variable for the `push docker image` step.
=> custom package dir
